# Generated by Django 5.0.3 on 2024-03-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='project',
        ),
    ]
