# Generated by Django 5.0.3 on 2024-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_post_like_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='project_is_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
