# Generated by Django 5.0.3 on 2024-03-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_like_project_is_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='project',
        ),
    ]
